repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
      - id: isort
        args: ["--profile", "black"]
        name: isort (cython)
        types: [cython]
      - id: isort
        args: ["--profile", "black"]
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: ^data/
      - id: check-yaml
      - id: no-commit-to-branch
        args: ["--branch", "master"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
